#!/bin/sh /etc/rc.common
START=80
STOP=20

USE_PROCD=1
EDGE_NAME="n2n"
CONFIGFILE="/etc/config/n2n.conf"
EDGE_IFACE="n2n0"                          # Default Edge Interface Name (Require)
ETH_IFACE="eth0"                           # Default Wlan Ethernet Interface Name (Require)
NET_RANGE="10.1.10.0/24"                    # Default Edge Network Range (Consistent with HOST_ADDR, Require)
LAN_RANGE="192.168.9.0/24"

start_service() {
        procd_open_instance
        procd_set_param command $EDGE_NAME $CONFIGFILE
        enable_rules
        enable_ipv4_forward
        procd_set_param file $CONFIGFILE
        procd_set_param respawn
        procd_close_instance
}

stop_service()
{
        disable_rules
        killall $EDGE_NAME > /dev/null 2>&1
}

service_triggers()
{
        procd_add_reload_trigger $CONFIGFILE
}

is_running(){
        if [ "`ps -ef | pgrep $EDGE_NAME | wc -l`" -eq "0" ]; then
                echo "$EDGE_NAME not running"
        else
                echo "$EDGE_NAME is running, pid is `ps -ef | pgrep $EDGE_NAME | xargs`"
        fi
}

check_ipv4_forward(){
        if [ "$(cat /proc/sys/net/ipv4/ip_forward)" -eq "1" ]; then
                echo 1
        else
                echo 0
        fi
}

enable_ipv4_forward(){
        pre_checking_forward=$(check_ipv4_forward)
        if [ "$pre_checking_forward" -eq 0 ]; then
                echo 1 > /proc/sys/net/ipv4/ip_forward
                echo "ipv4 forward enabled on system..."
        else
                echo "ipv4 forward already enabled on system..."
        fi
}

enable_rules(){
        nft list table ip n2nedge > /dev/null 2>&1 ;
        if [[ $? -ne 0 ]]; then
                nft add table ip n2nedge
                nft add chain ip n2nedge FORWARD { type filter hook forward priority filter\; }
                nft add chain ip n2nedge POSTROUTING { type nat hook postrouting priority srcnat\; }
        fi
        NAT_MASQUERADE=`nft -a list table n2nedge | grep "$NET_RANGE" | grep masquerade`
        if [ -z "$NAT_MASQUERADE" ]; then
                nft add rule ip n2nedge POSTROUTING ip saddr $NET_RANGE ip daddr $LAN_RANGE counter masquerade
                nft add rule ip n2nedge POSTROUTING oifname "$ETH_IFACE" counter masquerade
        fi


        echo "n2n rules in nftables is enable ..."
}

disable_rules(){
        nft flush chain ip n2nedge POSTROUTING
        nft flush chain ip n2nedge FORWARD 
        echo "n2n rules removed from nftables..."
}
